CREATE PROC FI_SP_ConsBeneficiario
	@IDCliente BIGINT
AS
BEGIN
	IF(ISNULL(@IDCliente,0) = 0)
		SELECT NOME, CPF, ID, IDCLIENTE FROM BENEFICIARIOS WITH(NOLOCK)
	ELSE
		SELECT NOME, CPF, ID, IDCLIENTE FROM BENEFICIARIOS WITH(NOLOCK) WHERE IDCliente = @IDCliente
END